#!/usr/bin/with-contenv bash
#     _         _       ____    ____
#    / \   _ __(_) __ _|___ \  |  _ \ _ __ ___
#   / _ \ | '__| |/ _` | __) | | |_) | '__/ _ \
#  / ___ \| |  | | (_| |/ __/  |  __/| | | (_) |
# /_/   \_\_|  |_|\__,_|_____| |_|   |_|  \___/
#
# https://github.com/P3TERX/Aria2-Pro-Docker
#
# Copyright (c) 2020-2021 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.

. /etc/init-base

if [[ -e "${ARIA2_CONF_DIR}/delete.sh" ]]; then
    rm -f "${ARIA2_CONF_DIR}"/*.sh
    sed -i "s@^\(on-download-stop=\).*@\1${SCRIPT_DIR}/delete.sh@" "${ARIA2_CONF}"
    sed -i "s@^\(on-download-complete=\).*@\1${SCRIPT_DIR}/clean.sh@" "${ARIA2_CONF}"
fi

sed -i "s@^\(dir=\).*@\1/downloads@" "${ARIA2_CONF}"
sed -i "s@^\(input-file=\).*@\1${ARIA2_CONF_DIR}/aria2.session@" "${ARIA2_CONF}"
sed -i "s@^\(save-session=\).*@\1${ARIA2_CONF_DIR}/aria2.session@" "${ARIA2_CONF}"
sed -i "s@^\(dht-file-path=\).*@\1${ARIA2_CONF_DIR}/dht.dat@" "${ARIA2_CONF}"
sed -i "s@^\(dht-file-path6=\).*@\1${ARIA2_CONF_DIR}/dht6.dat@" "${ARIA2_CONF}"

if [[ -e "${ARIA2_CONF_DIR}/HelloWorld" ]]; then
    exit 0
fi

if [[ -n "${RPC_PORT}" ]]; then
    sed -i "s@^\(rpc-listen-port=\).*@\1${RPC_PORT}@" "${ARIA2_CONF}"
fi

if [[ -n "${LISTEN_PORT}" ]]; then
    sed -i "s@^\(listen-port=\).*@\1${LISTEN_PORT}@" "${ARIA2_CONF}"
    sed -i "s@^\(dht-listen-port=\).*@\1${LISTEN_PORT}@" "${ARIA2_CONF}"
fi

if [[ -n "${RPC_SECRET}" ]]; then
    sed -i "s@^\(rpc-secret=\).*@\1${RPC_SECRET}@" "${ARIA2_CONF}"
fi

if [[ -n "${DISK_CACHE}" ]]; then
    sed -i "s@^\(disk-cache=\).*@\1${DISK_CACHE}@" "${ARIA2_CONF}"
fi

case "${IPV6_MODE}" in
    true|enable)
        sed -i "s@^\(disable-ipv6=\).*@\1false@" "${ARIA2_CONF}"
        sed -i "s@^\(enable-dht6=\).*@\1true@" "${ARIA2_CONF}"
        ;;
    false|disable)
        sed -i "s@^\(disable-ipv6=\).*@\1true@" "${ARIA2_CONF}"
        sed -i "s@^\(enable-dht6=\).*@\1false@" "${ARIA2_CONF}"
        ;;
esac

case "${SPECIAL_MODE}" in
    rclone)
        sed -i "s@^\(on-download-complete=\).*@\1${SCRIPT_DIR}/upload.sh@" "${ARIA2_CONF}"
        ;;
    move)
        sed -i "s@^\(on-download-complete=\).*@\1${SCRIPT_DIR}/move.sh@" "${ARIA2_CONF}"
        ;;
esac

exit 0
