#!/usr/bin/with-contenv bash
#     _         _       ____    ____
#    / \   _ __(_) __ _|___ \  |  _ \ _ __ ___
#   / _ \ | '__| |/ _` | __) | | |_) | '__/ _ \
#  / ___ \| |  | | (_| |/ __/  |  __/| | | (_) |
# /_/   \_\_|  |_|\__,_|_____| |_|   |_|  \___/
#
# https://github.com/P3TERX/Aria2-Pro-Docker
#
# Copyright (c) 2020-2021 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.

. /etc/init-base

if [[ -w "${DOWNLOAD_DIR}" ]]; then
    echo "Download DIR writeable, not changing owner."
else
    chown -R root:root "${DOWNLOAD_DIR}"
fi

chown -R root:root "${ARIA2_CONF_DIR}"

if [[ -w "${DOWNLOAD_DIR}" ]]; then
    echo "Download DIR writeable, not modifying permission."
else
    chmod u=rwx "${DOWNLOAD_DIR}"
fi

chmod 600 "${ARIA2_CONF_DIR}"/*
chmod 755 "${SCRIPT_DIR}"
chmod 700 "${SCRIPT_DIR}"/*
